a=[1,2,3,4,5,6]
# a.append([2])
# a.extend([2,3])
# a.insert(3,9)
# a.clear()
# b=a.del()
# a.copy()
# a.pop(4)
# a.remove(2)
# a.reverse()
# a.sort()
# b=a.reverse(int==True)
# b=a.count(5)
# print(b)
# a.index(6)
# a.__add__(5)
print(a)